# Exercise 4: Scaling techniques

# Preparation
```{r, echo=T, message=F ,warning=F, results='hide'}
# Packages
library(kableExtra)
library(dplyr)
library(quanteda)
library(quanteda.textmodels) # Textmodel_wordfish
library(quanteda.textplots) # Textplot_scale1d
library(ggplot2) # Bar plot

# Import Data
kaneko <- readRDS(gzcon(url("https://github.com/cjbarrie/CTA-ED/blob/main/data/wordscaling/study1_kaneko.rds?raw=true")))

# Check
glimpse(kaneko)
```

# Q1 Estimate a wordfish model for the @kaneko_estimating_2021 data
```{r}
# Group data by variable "Newspaper".
kaneko <- dfm_group(kaneko, groups = Newspaper)

# Trim data to remove words if not used by two or more newspapers
kaneko <- dfm_trim(kaneko, min_docfreq = 2, docfreq_type = "count")

# Check data: 10 rows and 4660 columns
dim(kaneko)

# Set a seed
set.seed(123L) 

# Apply wordfish: a model to analyze ideology
kaneko_wordfish <- textmodel_wordfish(kaneko, sparse = TRUE)

# Check
summary(kaneko_wordfish)
```

# Q2 Visualize the results.
```{r}
# Show the documents on one dimension of ideology
textplot_scale1d(kaneko_wordfish)

# Show the words on one dimension of ideology
textplot_scale1d(kaneko_wordfish, margin = "features") 

# Extract features
features <- kaneko_wordfish[["features"]]

# Extract beta: the influence of each word
betas <- kaneko_wordfish[["beta"]]

# A data frame of results
feat_betas <- data.frame(features = features, 
                         betas = as.numeric(betas))

# Kable of top 20
feat_betas %>%
  arrange(desc(betas)) %>%
  top_n(20) %>% 
  kbl() %>%
  kable_styling(bootstrap_options = "striped") 

# Bar plot of top 10
feat_betas %>%
  arrange(desc(betas)) %>%
  slice_max(betas, n = 10) %>%
  ggplot(aes(x = reorder(features, betas), y = betas)) + 
    geom_col(fill = "blue", alpha=0.5) +
    labs(title = "Top 10 Features by Beta Values", x = "Features", y = "Beta Values") +
    theme_minimal() +
    coord_flip()
```
